### ISSUE TITLE
NS_REFINED_FOR_SWIFT should be ignored by parser

### ISSUE THREAD

**Issue by rotemmiz** [DanielMSchmidt/objective-c-parser#52]
[NS_REFINED_FOR_SWIFT macro](https://github.com/google/EarlGrey/commit/499474e02cc486b65c360da362173ec77e7495ee#diff-ad85ec7ab42faaa4cd1a922503fca1caR18) was added to a few of EarlGrey's functions. 
This should be ignored when parsing objC code.

**Comment by DanielMSchmidt** [comment]
Fixed in version `1.2.3`
